### ISSUE TITLE
Discovered case where only 1 Authentication Type form section

### ISSUE THREAD

**Issue by MStasiw** [MStasiw/Configure_Xerox-WC-3615-6605#9]
https://github.com/MStasiw/Configure_Xerox-WC-3615-6605/blob/b09c1e2cb7c1f01de8819122ca0f6db8b0b8ef25/WC%203615%20%26%206605_Set%20Auth%20System-Kerberos%20%26%20LDAP%20servers.ps1#L149
Testing against mwbpr2.s03005.ca.wal-mart.com (WC 6605 on Controller Version: 201305012030), 'Authentication System' subsection HTTP POST fails because only one Authentication Type form section exists.

Only dropdown element named '102a02' which corresponds to 'Authentication Type (for Server Address/Phone Book)' exists, '102a03' is missing attempt to set it fails with HTTP 400 returned by server.

**Comment by MStasiw** [comment]
```
PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS pr1.s01203.ca.wal-mart.com -Verbose
VERBOSE: POST http://pr1.s01203.ca.wal-mart.com/setting/setkrb5.htm with -1-byte payload
VERBOSE: received 1879-byte response of content type text/html
pr1.s01203.ca.wal-mart.com	Status: 200 OK
VERBOSE: POST http://pr1.s01203.ca.wal-mart.com/setting/setldapsvr.htm with -1-byte payload
VERBOSE: received 3439-byte response of content type text/html
pr1.s01203.ca.wal-mart.com	Status: 200 OK
VERBOSE: POST http://pr1.s01203.ca.wal-mart.com/setting/setauthsys.htm with -1-byte payload
VERBOSE: received -1-byte response of content type text/html
pr1.s01203.ca.wal-mart.com	Status: 200 OK

PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS mwbpr1.s01207.ca.wal-mart.com -Verbose
VERBOSE: POST http://mwbpr1.s01207.ca.wal-mart.com/setting/setkrb5.htm with -1-byte payload
VERBOSE: received 1879-byte response of content type text/html
mwbpr1.s01207.ca.wal-mart.com	Status: 200 OK
VERBOSE: POST http://mwbpr1.s01207.ca.wal-mart.com/setting/setldapsvr.htm with -1-byte payload
VERBOSE: received 3758-byte response of content type text/html
mwbpr1.s01207.ca.wal-mart.com	Status: 200 OK
VERBOSE: POST http://mwbpr1.s01207.ca.wal-mart.com/setting/setauthsys.htm with -1-byte payload
VERBOSE: received -1-byte response of content type text/html
mwbpr1.s01207.ca.wal-mart.com	Status: 200 OK

PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS mwbpr2.s03005.ca.wal-mart.com -Verbose
VERBOSE: POST http://mwbpr2.s03005.ca.wal-mart.com/setting/setkrb5.htm with -1-byte payload
VERBOSE: received -1-byte response of content type text/html
mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
VERBOSE: POST http://mwbpr2.s03005.ca.wal-mart.com/setting/setldapsvr.htm with -1-byte payload
VERBOSE: received -1-byte response of content type text/html
mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
VERBOSE: POST http://mwbpr2.s03005.ca.wal-mart.com/setting/setauthsys.htm with -1-byte payload
WARNING: IP/DNS Address = mwbpr2.s03005.ca.wal-mart.com
WARNING: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()

PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS mwbpr2.s03005.ca.wal-mart.com -Debug
DEBUG: mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
DEBUG: mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK

WARNING: IP/DNS Address = mwbpr2.s03005.ca.wal-mart.com
WARNING: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
DEBUG: $ReturnCode = 3
```

![image](https://user-images.githubusercontent.com/6655810/214563031-848dd367-f4ba-4370-ba11-8250ef34ce16.png)

**Comment by MStasiw** [comment]
> ```
> PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS pr1.s01203.ca.wal-mart.com -Verbose
> VERBOSE: POST http://pr1.s01203.ca.wal-mart.com/setting/setkrb5.htm with -1-byte payload
> VERBOSE: received 1879-byte response of content type text/html
> pr1.s01203.ca.wal-mart.com	Status: 200 OK
> VERBOSE: POST http://pr1.s01203.ca.wal-mart.com/setting/setldapsvr.htm with -1-byte payload
> VERBOSE: received 3439-byte response of content type text/html
> pr1.s01203.ca.wal-mart.com	Status: 200 OK
> VERBOSE: POST http://pr1.s01203.ca.wal-mart.com/setting/setauthsys.htm with -1-byte payload
> VERBOSE: received -1-byte response of content type text/html
> pr1.s01203.ca.wal-mart.com	Status: 200 OK
> 
> PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS mwbpr1.s01207.ca.wal-mart.com -Verbose
> VERBOSE: POST http://mwbpr1.s01207.ca.wal-mart.com/setting/setkrb5.htm with -1-byte payload
> VERBOSE: received 1879-byte response of content type text/html
> mwbpr1.s01207.ca.wal-mart.com	Status: 200 OK
> VERBOSE: POST http://mwbpr1.s01207.ca.wal-mart.com/setting/setldapsvr.htm with -1-byte payload
> VERBOSE: received 3758-byte response of content type text/html
> mwbpr1.s01207.ca.wal-mart.com	Status: 200 OK
> VERBOSE: POST http://mwbpr1.s01207.ca.wal-mart.com/setting/setauthsys.htm with -1-byte payload
> VERBOSE: received -1-byte response of content type text/html
> mwbpr1.s01207.ca.wal-mart.com	Status: 200 OK
> 
> PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS mwbpr2.s03005.ca.wal-mart.com -Verbose
> VERBOSE: POST http://mwbpr2.s03005.ca.wal-mart.com/setting/setkrb5.htm with -1-byte payload
> VERBOSE: received -1-byte response of content type text/html
> mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
> VERBOSE: POST http://mwbpr2.s03005.ca.wal-mart.com/setting/setldapsvr.htm with -1-byte payload
> VERBOSE: received -1-byte response of content type text/html
> mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
> VERBOSE: POST http://mwbpr2.s03005.ca.wal-mart.com/setting/setauthsys.htm with -1-byte payload
> WARNING: IP/DNS Address = mwbpr2.s03005.ca.wal-mart.com
> WARNING: System.Net.WebException: The remote server returned an error: (400) Bad Request.
>    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
>    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
> 
> PS > & '.\WC 3615 & 6605_Set Auth System-Kerberos & LDAP servers.ps1' -IPorDNS mwbpr2.s03005.ca.wal-mart.com -Debug
> DEBUG: mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
> DEBUG: mwbpr2.s03005.ca.wal-mart.com	Status: 200 OK
> 
> WARNING: IP/DNS Address = mwbpr2.s03005.ca.wal-mart.com
> WARNING: System.Net.WebException: The remote server returned an error: (400) Bad Request.
>    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
>    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
> DEBUG: $ReturnCode = 3
> ```
> 
> ![image](https://user-images.githubusercontent.com/6655810/214563031-848dd367-f4ba-4370-ba11-8250ef34ce16.png)

Upon investigating if same situation on all WC 6605's on Controller Version: 201305012030, the are only two but both in exact same situation.
Therefore assuming this was an oversight and missing in firmware of Controller Version: 201305012030
